# Generated by Django 4.0.5 on 2022-07-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_paretosuser_email_confirmation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='paretosuser',
            name='password_reset_token',
            field=models.IntegerField(default=0),
        ),
    ]
